SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using SkyCommerce.ViewObjects;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

namespace SkyCommerce.Site.Controllers
{
    [Route("catalogo")]
    public class CatalogoController : Controller
    {
        private readonly IProdutoStore _produtoStore;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IFreteService _freteService;
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaStore _categoriaStore;
        private readonly IMarcaStore _marcaStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CatalogoController(
            IProdutoStore produtoStore,
            IGeoposicaoService geoposicaoService,
            IFreteService freteService,
            IProdutoService produtoService,
            ICategoriaStore categoriaStore,
            IMarcaStore marcaStore,
            IHttpContextAccessor httpContextAccessor
            )
        {
            _produtoStore = produtoStore;
            _geoposicaoService = geoposicaoService;
            _freteService = freteService;
            _produtoService = produtoService;
            _categoriaStore = categoriaStore;
            _marcaStore = marcaStore;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Route("{produto}")]
        public async Task<IActionResult> Detalhes(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            var produtosRelacionados = await _produtoStore.ObterPorCategoria(produtoDetails.Categorias.FirstOrDefault());

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");

            var frete = await _freteService.ObterModalidades(at);

            return View(new ProdutoDetalhesViewModel()
            {
                Produto = produtoDetails,
                ProdutosRelacionados = produtosRelacionados.Where(w => w.NomeUnico != produtoDetails.NomeUnico).Take(6),
                OpcoesFrete = frete,
            });
        }

        private async Task<string> GeolocalizarUsuario()
        {
            var posicaoDoGuerreiro = Request.Cookies["geoposicao"];
            if (posicaoDoGuerreiro == null)
            {
                var localizacaoDoUsuario = await _geoposicaoService.ObterLocalizacaoAtual();
                posicaoDoGuerreiro = localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude;
                Response.Cookies.Append("geoposicao", localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude);
            }

            return posicaoDoGuerreiro;
        }

        [Route("visualizar/{produto}")]
        public async Task<IActionResult> PreVisualizar(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            return PartialView("Produtos/_Visualizar", produtoDetails);
        }

        [Route("comentar/{produto}")]
        public async Task<IActionResult> Comentar(string produto, [FromForm] Avaliacao avaliacao)
        {
            avaliacao.ProdutoUrl = produto;
            avaliacao.Imagem = "/images/site/default-user.png";
            await _produtoService.Comentar(avaliacao);
            return RedirectToAction("Detalhes", new { produto });
        }


        [Route("marcas/{marca}")]
        public async Task<IActionResult> Marca(string marca, [FromQuery] PesquisarProdutoVo model)
        {
            model.Marca = marca;
            var marcaDetalhes = await _marcaStore.ObterPorNome(marca);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorMarca(model),
                ImagemCapa = marcaDetalhes?.Imagem,
                Titulo = marcaDetalhes?.Nome,
                SubTitulo = string.Empty,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Route("pedidos"), Authorize]
    public class PedidosController : Controller
    {
        private readonly IPedidoStore _pedidoStore;

        public PedidosController(IPedidoStore pedidoStore)
        {
            _pedidoStore = pedidoStore;
        }

        public async Task<IActionResult> Index()
        {
            var pedidos = await _pedidoStore.ListarPedidos(User.Identity.Name);
            return View(pedidos);
        }

        [Route("{identificador}")]
        public async Task<IActionResult> Detalhes(string identificador)
        {
            var pedido = await _pedidoStore.ObterPorIdentificador(identificador, User.Identity.Name);
            return View(pedido);
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Pedidos/Detalhes.cshtml
@using Humanizer
@using SkyCommerce.Extensions
@using SkyCommerce.Models
@model SkyCommerce.Models.Pedido
<div class="container main-container headerOffset">
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
            <ul class="breadcrumb">

                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Account" asp-action="MinhaConta">Minha conta</a></li>
                <li><a asp-controller="Pedidos" asp-action="Index">Pedidos</a></li>
                <li class="active">#@Model.IdentificadorUnico</li>
            </ul>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-7">
            <h1 class="section-title-inner"><span><i class="fa fa-list-alt"></i> Pedido </span></h1>

            <div class="row userInfo">
                <div class="col-lg-12">
                    <h2 class="block-title-2"> Detalhes do seu Pedido </h2>
                </div>


                <div class="statusContent">


                    <div class="col-sm-12">
                        <div class=" statusTop">
                            <p><strong>Status:</strong> @Model.StatusPedido</p>

                            <p><strong>Data do pedido:</strong> @Model.DataPagamento.Humanize()</p>

                            <p><strong>Pedido:</strong> #@Model.IdentificadorUnico </p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="order-box">
                            <div class="order-box-header">

                                Endereço de cobrança
                            </div>


                            <div class="order-box-content">
                                <div class="address">
                                    <p><strong>@Model.EnderecoCobranca.Nome </strong></p>

                                    <p><strong>@Model.EnderecoCobranca.Sobrenome </strong></p>

                                    <div class="adr">
                                        @Model.EnderecoCobranca.Logradouro, @Model.EnderecoCobranca.Bairro @Model.EnderecoCobranca.Cidade - @Model.EnderecoCobranca.Estado, CEP: @Model.EnderecoCobranca.Cep
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <div class="col-sm-6">
                        <div class="order-box">
                            <div class="order-box-header">

                                Endereço de entrega
                            </div>


                            <div class="order-box-content">


                                <div class="address">
                                    <p><strong>@Model.EnderecoEntrega.Nome </strong></p>

                                    <p><strong>@Model.EnderecoEntrega.Sobrenome </strong></p>

                                    <div class="adr">
                                        @Model.EnderecoEntrega.Logradouro, @Model.EnderecoEntrega.Bairro @Model.EnderecoEntrega.Cidade - @Model.EnderecoEntrega.Estado, CEP: @Model.EnderecoEntrega.Cep
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>

                    <div style="clear: both"></div>

                    <div class="col-sm-6">
                        <div class="order-box">
                            <div class="order-box-header">

                                Metodo de pagamento
                            </div>


                            <div class="order-box-content">
                                <div class="address">
                                    <p>
                                        Pagamento feito via @Model.TipoPagamento
                                    </p>
                                    @if (Model.TipoPagamento == TipoPagamento.CartaoCredito)
                                    {
                                        <p><strong>Nome no Cartao: </strong> @Model.Cartao.Nome </p>

                                        <p><strong>Cartão: </strong> @Model.Cartao.Numero </p>
                                    }


                                </div>
                            </div>
                        </div>

                    </div>


                    <div class="col-sm-6">
                        <div class="order-box">
                            <div class="order-box-header">

                                Frete
                            </div>


                            <div class="order-box-content">
                                <div class="address">
                                    @if (Model.Frete.Modalidade == "Gratis")
                                    {
                                        <p>  Frete gratuito</p>
                                    }
                                    else
                                    {
                                        <p> via @Model.Frete.Modalidade <span title="tracking number">#@Model.RastreamentoFrete</span></p>
                                    }

                                </div>

                            </div>
                        </div>

                    </div>


                    <div class="col-sm-12 clearfix">
                        <div class="order-box">
                            <div class="order-box-header">

                                Produtos
                            </div>


                            <div class="order-box-content">
                                <div class="table-responsive">
                                    <table class="order-details-cart">
                                        <tbody>
                                            @foreach (var item in Model.Produtos)
                                            {
                                                <tr class="cartProduct">
                                                    <td class="cartProductThumb" style="width: 20%">
                                                        <div>
                                                            <a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico">
                                                                <img src="@item.Imagem" alt="@item.Nome">
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td style="width: 40%">
                                                        <div class="miniCartDescription">
                                                            <h4><a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico"> @item.Nome </a></h4>

                                                            <div class="price"><span> @item.Valor.ToString("C") </span></div>
                                                        </div>
                                                    </td>
                                                    <td class="" style="width: 10%"><a> X @item.Quantidade </a></td>
                                                    <td class="" style="width: 15%"><span> @item.Total.ToString("C") </span></td>

                                                </tr>
                                            }

                                            <tr class="cartTotalTr blank">
                                                <td class="" style="width: 20%">
                                                    <div></div>
                                                </td>
                                                <td style="width: 40%"></td>
                                                <td class="" style="width: 20%"></td>
                                                <td class="" style="width: 15%"><span> </span></td>

                                            </tr>

                                            <tr class="cartTotalTr">
                                                <td class="" style="width: 20%">
                                                    <div></div>
                                                </td>
                                                <td colspan="2" style="width: 40%">Total produtos</td>
                                                <td class="" style="width: 15%"><span> @Model.TotalProdutos.ToString("C") </span></td>

                                            </tr>
                                            <tr class="cartTotalTr">
                                                <td class="" style="width: 20%">
                                                    <div></div>
                                                </td>
                                                <td colspan="2" style="width: 40%">Entrega</td>
                                                <td class="" style="width: 15%">
                                                    @if (Model.Frete.Modalidade == "Gratis")
                                                    {
                                                        <span>Gratuito</span>
                                                    }
                                                    else
                                                    {
                                                        <span>@Model.Frete.Valor.ToString("C")</span>
                                                    }
                                                </td>

                                            </tr>
                                            <tr class="cartTotalTr">
                                                <td class="" style="width: 20%">
                                                    <div></div>
                                                </td>
                                                <td colspan="2" style="width: 40%">Total sem impostos</td>
                                                <td class="" style="width: 15%"><span> @Model.TotalSemImposto.ToString("C") </span></td>

                                            </tr>
                                            <tr class="cartTotalTr">
                                                <td class="" style="width: 20%">
                                                    <div></div>
                                                </td>
                                                <td style="width: 40%"></td>
                                                <td class="" style="width: 20%">Total</td>
                                                <td class="" style="width: 15%"><span class="price"> @Model.Total.ToString("C") </span></td>

                                            </tr>


                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>

                    </div>
                    @if (Model.Comentario.IsPresent())
                    {
                        <div class="col-sm-12">
                            <div class="order-box">
                                <div class="order-box-header">

                                    Observações
                                </div>


                                <div class="order-box-content">
                                    <p>@Model.Comentario</p>
                                </div>
                            </div>

                        </div>
                    }

                </div>


                <div class="col-lg-12 clearfix">
                    <ul class="pager">
                        <li class="previous pull-right">
                            <a asp-controller="Home" asp-action="Index"> <i class="fa fa-home"></i> Comprar </a>
                        </li>
                        <li class="next pull-left"><a asp-controller="Pedidos" asp-action="Index"> &larr; Voltar</a></li>
                    </ul>
                </div>
            </div>
            <!--/row end-->

        </div>
        <div class="col-lg-3 col-md-3 col-sm-5"></div>
    </div>
    <!--/row-->

    <div style="clear:both"></div>
</div>
<!-- /main-container -->

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Pedidos/Index.cshtml
@using SkyCommerce.Extensions
@using Humanizer
@using SkyCommerce.Models
@model IEnumerable<SkyCommerce.Models.Pedido>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    <!-- styles needed by footable  -->
    <link href="assets/css/footable-0.1.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/footable.sortable-0.1.css" rel="stylesheet" type="text/css" />
}
@section Scripts
{
    <script src="assets/js/footable.js" type="text/javascript"></script>
    <script src="assets/js/footable.sortable.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('.footable').footable();
        });
    </script>
}



<div class="container main-container headerOffset">
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
            <ul class="breadcrumb">

                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Account" asp-action="MinhaConta">Minha conta</a></li>
                <li class="active">Pedidos</li>
            </ul>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-7">
            <h1 class="section-title-inner"><span><i class="fa fa-list-alt"></i> Pedidos </span></h1>

            <div class="row userInfo">
                <div class="col-lg-12">
                    <h2 class="block-title-2"> Seus pedidos </h2>
                </div>

                <div style="clear:both"></div>

                <div class="col-xs-12 col-sm-12">
                    <table class="footable">
                        <thead>
                            <tr>
                                <th data-class="expand" data-sort-initial="true">
                                    <span>Identificador</span>
                                </th>
                                <th data-hide="phone,tablet" data-sort-ignore="true">Produtos</th>
                                <th data-hide="phone,tablet"><strong>Método Pagamento</strong></th>
                                <th data-hide="default"> Valor</th>
                                <th data-hide="default" data-type="numeric"> Data</th>
                                <th data-hide="phone" data-type="numeric"> Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var pedido in Model)
                            {
                                <tr>
                                    <td><a asp-action="Detalhes" asp-controller="Pedidos" asp-route-identificador="@pedido.IdentificadorUnico">@pedido.IdentificadorUnico</a></td>
                                    <td>
                                        @pedido.QuantidadeProdutos
                                        <small>item(s)</small>
                                    </td>
                                    <td>@pedido.TipoPagamento.ToString()</td>
                                    <td>@pedido.Total.ToString("C")</td>
                                    <td>@pedido.DataPagamento.Humanize()</td>
                                    <td data-value="3">

                                        @switch (pedido.StatusPedido)
                                        {
                                            case StatusPedido.Processando:
                                                <span class="label label-warning">Processando</span>
                                                break;
                                            case StatusPedido.SeparandoParaEnvio:
                                                <span class="label label-warning">Separado para envio</span>
                                                break;
                                            case StatusPedido.Enviado:
                                                <span class="label label-info">Enviado</span>
                                                break;
                                            case StatusPedido.Finalizado:
                                                <span class="label label-success">Finalizado</span>
                                                break;
                                            case StatusPedido.Cancelado:
                                                <span class="label label-default">Cancelado</span>
                                                break;
                                            case StatusPedido.PagamentoNegado:
                                                <span class="label label-danger">Erro no pagamento</span>
                                                break;
                                            case StatusPedido.AguardandoConfirmacao:
                                                <span class="label label-warning">Aguardando confirmacao</span>
                                                break;
                                        }

                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>

                <div style="clear:both"></div>

                <div class="col-lg-12 clearfix">
                    <ul class="pager">
                        <li class="previous pull-right">
                            <a asp-controller="Home" asp-action="Index"> <i class="fa fa-home"></i> Comprar </a>
                        </li>
                        <li class="next pull-left"><a asp-controller="Account" asp-action="MinhaConta"> &larr; Voltar</a></li>
                    </ul>
                </div>
            </div>
            <!--/row end-->

        </div>
        <div class="col-lg-3 col-md-3 col-sm-5"></div>
    </div>
    <!--/row-->

    <div style="clear:both"></div>
</div>
<!-- /main-container -->