SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using SkyCommerce.ViewObjects;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

namespace SkyCommerce.Site.Controllers
{
    [Route("catalogo")]
    public class CatalogoController : Controller
    {
        private readonly IProdutoStore _produtoStore;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IFreteService _freteService;
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaStore _categoriaStore;
        private readonly IMarcaStore _marcaStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CatalogoController(
            IProdutoStore produtoStore,
            IGeoposicaoService geoposicaoService,
            IFreteService freteService,
            IProdutoService produtoService,
            ICategoriaStore categoriaStore,
            IMarcaStore marcaStore,
            IHttpContextAccessor httpContextAccessor
            )
        {
            _produtoStore = produtoStore;
            _geoposicaoService = geoposicaoService;
            _freteService = freteService;
            _produtoService = produtoService;
            _categoriaStore = categoriaStore;
            _marcaStore = marcaStore;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Route("{produto}")]
        public async Task<IActionResult> Detalhes(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            var produtosRelacionados = await _produtoStore.ObterPorCategoria(produtoDetails.Categorias.FirstOrDefault());

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");

            var frete = await _freteService.ObterModalidades(at);

            return View(new ProdutoDetalhesViewModel()
            {
                Produto = produtoDetails,
                ProdutosRelacionados = produtosRelacionados.Where(w => w.NomeUnico != produtoDetails.NomeUnico).Take(6),
                OpcoesFrete = frete,
            });
        }

        private async Task<string> GeolocalizarUsuario()
        {
            var posicaoDoGuerreiro = Request.Cookies["geoposicao"];
            if (posicaoDoGuerreiro == null)
            {
                var localizacaoDoUsuario = await _geoposicaoService.ObterLocalizacaoAtual();
                posicaoDoGuerreiro = localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude;
                Response.Cookies.Append("geoposicao", localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude);
            }

            return posicaoDoGuerreiro;
        }

        [Route("visualizar/{produto}")]
        public async Task<IActionResult> PreVisualizar(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            return PartialView("Produtos/_Visualizar", produtoDetails);
        }

        [Route("comentar/{produto}")]
        public async Task<IActionResult> Comentar(string produto, [FromForm] Avaliacao avaliacao)
        {
            avaliacao.ProdutoUrl = produto;
            avaliacao.Imagem = "/images/site/default-user.png";
            await _produtoService.Comentar(avaliacao);
            return RedirectToAction("Detalhes", new { produto });
        }


        [Route("marcas/{marca}")]
        public async Task<IActionResult> Marca(string marca, [FromQuery] PesquisarProdutoVo model)
        {
            model.Marca = marca;
            var marcaDetalhes = await _marcaStore.ObterPorNome(marca);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorMarca(model),
                ImagemCapa = marcaDetalhes?.Imagem,
                Titulo = marcaDetalhes?.Nome,
                SubTitulo = string.Empty,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Site.Models;
using SkyCommerce.ViewObjects;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Route("categorias")]
    public class CategoriasController : Controller
    {
        private readonly ICategoriaStore _categoriaStore;
        private readonly IProdutoStore _produtoStore;
        private readonly IMarcaStore _marcaStore;

        public CategoriasController(ICategoriaStore categoriaStore, IProdutoStore produtoStore, IMarcaStore marcaStore)
        {
            _categoriaStore = categoriaStore;
            _produtoStore = produtoStore;
            _marcaStore = marcaStore;
        }

        [Route("{categoria}")]
        public async Task<IActionResult> Index(string categoria, [FromQuery] PesquisarProdutoVo model)
        {
            model.Categoria = categoria.ToLower();
            var categoriaData = await _categoriaStore.ObterPorNome(categoria);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorCategoria(model),
                ImagemCapa = categoriaData?.ImagemCapa,
                Titulo = categoriaData?.Nome,
                SubTitulo = categoriaData?.Descricao,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Shared/Produtos/_Categoria.cshtml
@model SkyCommerce.Models.Categoria

<div class="col-md-2 col-sm-3 col-xs-4  col-xs-mini-6  text-center ">
    <div class="thumbnail">
        <a class="subCategoryThumb" asp-controller="Categorias" asp-action="Index" asp-route-categoria="@Model.NomeUnico">
            <img src="@Model.Imagem" class="img-rounded " alt="img">
        </a> <a class="subCategoryTitle"><span> @Model.Nome </span></a>
    </div>
</div>

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Shared/Produtos/_Produto.cshtml
@model SkyCommerce.Models.Produto
<div class="product">
    <a class="add-fav tooltipHere" data-toggle="tooltip"
       data-original-title="Adicionar aos favoritos" data-placement="left">
        <i class="glyphicon glyphicon-heart"></i>
    </a>

    <div class="image">
        <div class="quickview">
            <a data-toggle="modal" class="btn btn-xs btn-quickview" asp-controller="Catalogo" asp-action="PreVisualizar" asp-route-produto="@Model.NomeUnico"
               data-target="#productSetailsModalAjax">Visualizar </a>
        </div>
        <a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico">
            <img src="@Model.Imagem" alt="img" class="img-responsive">
        </a>

        <div class="promotion">
            @if (Model.Novo)
            {
                <span class="new-product"> NOVO</span>
            }
            @if (Model.Valor * 1.15m < Model.ValorAntigo)
            {
                <span class="discount">
                    @Model.TextoPercentualDesconto()

                </span>
            }
        </div>

    </div>
    <div class="description">
        <h4><a asp-action="Detalhes" asp-controller="Catalogo" asp-route-produto="@Model.NomeUnico">@Model.Nome </a></h4>

        <p>@Model.Descricao </p>
        @foreach (var categoia in Model.Categorias)
        {
            <span class="size"><a asp-controller="Categorias" asp-action="Index" asp-route-categoria="@categoia.ToLower()">@categoia</a>&nbsp;></span>
        }

    </div>
    <div class="price"><span>@Model.Valor.ToString("C")</span></div>
    <div class="action-control">
        <form asp-controller="Carrinho" asp-action="Adicionar">
            <input type="hidden" name="NomeUnico" value="@Model.NomeUnico" />
            <button class="btn btn-primary" type="submit">
                <span class="add2cart">
                    <i class="glyphicon glyphicon-shopping-cart"> </i> Adicionar ao carrinho
                </span>
            </button>
        </form>
    </div>
</div>
<!--/.produto-->

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Shared/Produtos/_ProdutosSimples.cshtml
@model SkyCommerce.Models.Produto
<div class="product">
    <a class="product-image" asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico"> <img src="@Model.Imagem" alt="img"> </a>

    <div class="description">
        <h4><a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico">@Model.Nome</a></h4>

        <div class="price"><span>@Model.Valor.ToString("C")</span></div>
    </div>
</div>
<!--/.item-->

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Shared/Produtos/_Visualizar.cshtml
@model SkyCommerce.Models.Produto
@{
    string currentUrl = Context.Request.Scheme + "://" + Context.Request.Host + @Url.Action("Detalhes", "Catalogo", new { produto = Model.NomeUnico });
    string enc = System.Net.WebUtility.UrlEncode(currentUrl);
    string text = System.Net.WebUtility.UrlEncode(Model.Nome);
}
<button aria-hidden="true" data-dismiss="modal" class="close" type="button"> ×</button>
<div class="col-lg-5 col-md-5 col-sm-5  col-xs-12">

    <!-- product Image -->
    <div class="main-image  col-lg-12 no-padding style3">
        <a class="product-largeimg-link" asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico">
            <img src="@Model.Imagem"
                 class="img-responsive product-largeimg"
                 alt="img">
        </a>
    </div>
    <!--/.main-image-->

    <div class="modal-product-thumb">
        <a class="thumbLink selected">
            <img data-large="@Model.Imagem" alt="img" class="img-responsive" src="@Model.Imagem">
        </a>
        @foreach (var imagem in Model.Imagens)
        {
            <a class="thumbLink selected">
                <img data-large="@imagem" alt="img" class="img-responsive" src="@imagem">
            </a>
        }
    </div>
    <!--/.modal-product-thumb-->
</div>
<!--/ product Image-->


<div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 modal-details no-padding">
    <div class="modal-details-inner">
        <h1 class="product-title"> @Model.Nome</h1>

        <h3 class="product-code">Codigo : @Model.Codigo</h3>

        <div class="product-price">
            <span class="price-sales"> @Model.Valor.ToString("C")</span> <span class="price-standard">@Model.ValorAntigo.ToString("C")</span>
        </div>
        <div class="details-description">
            <p>@Model.Descricao </p>
        </div>
        <div class="color-details">
            <span class="selected-color"><strong>COR</strong></span>
            <ul class="swatches Color">
                <li class="selected">
                    <a style="background-color:#f1f40e"> </a>
                </li>
                <li>
                    <a style="background-color:#adadad"> </a>
                </li>
                <li>
                    <a style="background-color:#4EC67F"> </a>
                </li>
            </ul>
        </div>
        <!--/.color-details-->


        <div class="cart-actions">
            <div class="addto row">
                <div class="col-lg-6">
                    <form asp-controller="Carrinho" asp-action="Adicionar">
                        <input type="hidden" name="NomeUnico" value="@Model.NomeUnico" />
                        <button class="button btn-block btn-cart cart first" title="Adicionar ao Carrinho"
                                type="submit">
                            Adicionar ao Carrinho
                        </button>
                    </form>

                </div>
            </div>
        </div>
        <!--/.cart-actions-->

        <div class="product-share clearfix">
            <p> Compartilhe </p>

            <div class="socialIcon">
                <a href="https://www.facebook.com/sharer/sharer.php?u=@enc" target="_blank" rel="noopener noreferrer nofollow">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="https://twitter.com/intent/tweet?url=@enc&text=@text" target="_blank" rel="noopener noreferrer nofollow">
                    <i class="fa fa-twitter"></i>
                </a>
            </div>
        </div>
        <!--/.product-share-->
    </div>
    <!--/.modal-details-inner-->
</div>
<!--/.modal-details-->
<div class="clear"></div>

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Shared/Produtos/_Vitrine.cshtml
@model SkyCommerce.Models.Produto

<div class="product-slide">
    <div class="col-sm-5 product-slide-left">
        <a class="product-slide-img" asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico">
            <img alt="img"
                 src="@Model.Imagem"
                 class="img-responsive">
        </a>
    </div>
    <div class="col-sm-7">
        <a class="product-slide-inner " asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@Model.NomeUnico">
            <h1 class="product-title"> @Model.Nome</h1>

            <h3 class="product-code">Codigo : @Model.Codigo</h3>

            <div class="product-price">
                <span class="price-sales"> @Model.Valor.ToString("C")</span> <span class="price-standard">@Model.ValorAntigo.ToString("C")</span>
            </div>
            <div class="details-description">
                <p>
                    @Model.Descricao
                </p>
            </div>
        </a>
        <form asp-controller="Carrinho" asp-action="Adicionar">
            <input type="hidden" name="NomeUnico" value="@Model.NomeUnico" />
            <button title="Adicionar no carrinho" class="btn btn-stroke-dark" type="submit">
                <i class="glyphicon glyphicon-shopping-cart"></i> Adicionar no carrinho
            </button>
        </form>

    </div>
</div>