SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Models/CarrinhoViewModel.cs
using SkyCommerce.Models;
using System.Collections.Generic;
using SkyCommerce.ViewObjects;

namespace SkyCommerce.Site.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }
        public IEnumerable<Frete> Fretes { get; set; }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CarrinhoController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Extensions;
using SkyCommerce.Interfaces;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Route("carrinho"), Authorize]
    public class CarrinhoController : Controller
    {
        private readonly ICarrinhoService _carrinhoService;
        private readonly ICarrinhoStore _carrinhoStore;
        private readonly IFreteService _freteService;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IProdutoStore _produtoStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CarrinhoController(
            ICarrinhoService carrinhoService,
            ICarrinhoStore carrinhoStore,
            IFreteService freteService,
            IGeoposicaoService geoposicaoService,
            IProdutoStore produtoStore,
            IHttpContextAccessor httpContextAccessor)
        {
            _carrinhoService = carrinhoService;
            _carrinhoStore = carrinhoStore;
            _freteService = freteService;
            _geoposicaoService = geoposicaoService;
            _produtoStore = produtoStore;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var fretes = await _freteService.CalcularCarrinho(carrinho, await _geoposicaoService.GeolocalizarUsuario(), at);
            return View(new CarrinhoViewModel()
            {
                Carrinho = carrinho,
                Fretes = fretes
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("cupom")]
        public async Task<IActionResult> Cupom(string returnurl, DescontoCarrinhoViewModel model)
        {
            await _carrinhoService.AplicarCupom(model.Cupom, User.Identity.Name);

            if (returnurl.IsPresent())
                return Redirect(returnurl);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("quantidade")]
        public async Task<IActionResult> Quantidade(AtualizarQuantidadeCarrinhoViewModel model)
        {
            await _carrinhoService.AtualizarQuantidadeProduto(User.Identity.Name, model.NomeUnico, model.Quantidade);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("remover")]
        public async Task<IActionResult> Remover(RemoverProdutoCarrinhoViewModel model)
        {
            await _carrinhoService.Remover(model.NomeUnico, User.Identity.Name);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("adicionar")]
        public async Task<IActionResult> Adicionar(AdicionarProdutoCarrinhoViewModel model)
        {
            var produto = await _produtoStore.ObterPorNome(model.NomeUnico);
            await _carrinhoService.AdicionarProduto(User.Identity.Name, produto, 1);

            return RedirectToAction(nameof(HomeController.Index), "Carrinho");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("selecionar-frete")]
        public async Task<IActionResult> SelecionarFrete(string returnurl, [FromForm] SelecionarFreteViewModel model)
        {

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            await _carrinhoService.SelecionarFrete(User.Identity.Name, model.Modalidade, await _geoposicaoService.GeolocalizarUsuario(), at);

            if (returnurl.IsPresent())
                return Redirect(returnurl);
            return RedirectToAction(nameof(HomeController.Index), "Carrinho");
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using SkyCommerce.ViewObjects;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

namespace SkyCommerce.Site.Controllers
{
    [Route("catalogo")]
    public class CatalogoController : Controller
    {
        private readonly IProdutoStore _produtoStore;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IFreteService _freteService;
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaStore _categoriaStore;
        private readonly IMarcaStore _marcaStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CatalogoController(
            IProdutoStore produtoStore,
            IGeoposicaoService geoposicaoService,
            IFreteService freteService,
            IProdutoService produtoService,
            ICategoriaStore categoriaStore,
            IMarcaStore marcaStore,
            IHttpContextAccessor httpContextAccessor
            )
        {
            _produtoStore = produtoStore;
            _geoposicaoService = geoposicaoService;
            _freteService = freteService;
            _produtoService = produtoService;
            _categoriaStore = categoriaStore;
            _marcaStore = marcaStore;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Route("{produto}")]
        public async Task<IActionResult> Detalhes(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            var produtosRelacionados = await _produtoStore.ObterPorCategoria(produtoDetails.Categorias.FirstOrDefault());

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");

            var frete = await _freteService.ObterModalidades(at);

            return View(new ProdutoDetalhesViewModel()
            {
                Produto = produtoDetails,
                ProdutosRelacionados = produtosRelacionados.Where(w => w.NomeUnico != produtoDetails.NomeUnico).Take(6),
                OpcoesFrete = frete,
            });
        }

        private async Task<string> GeolocalizarUsuario()
        {
            var posicaoDoGuerreiro = Request.Cookies["geoposicao"];
            if (posicaoDoGuerreiro == null)
            {
                var localizacaoDoUsuario = await _geoposicaoService.ObterLocalizacaoAtual();
                posicaoDoGuerreiro = localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude;
                Response.Cookies.Append("geoposicao", localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude);
            }

            return posicaoDoGuerreiro;
        }

        [Route("visualizar/{produto}")]
        public async Task<IActionResult> PreVisualizar(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            return PartialView("Produtos/_Visualizar", produtoDetails);
        }

        [Route("comentar/{produto}")]
        public async Task<IActionResult> Comentar(string produto, [FromForm] Avaliacao avaliacao)
        {
            avaliacao.ProdutoUrl = produto;
            avaliacao.Imagem = "/images/site/default-user.png";
            await _produtoService.Comentar(avaliacao);
            return RedirectToAction("Detalhes", new { produto });
        }


        [Route("marcas/{marca}")]
        public async Task<IActionResult> Marca(string marca, [FromQuery] PesquisarProdutoVo model)
        {
            model.Marca = marca;
            var marcaDetalhes = await _marcaStore.ObterPorNome(marca);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorMarca(model),
                ImagemCapa = marcaDetalhes?.Imagem,
                Titulo = marcaDetalhes?.Nome,
                SubTitulo = string.Empty,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkyCommerce.Interfaces;
using SkyCommerce.Models;
using SkyCommerce.Site.Models;
using SkyCommerce.Site.Service;
using System.Threading.Tasks;

namespace SkyCommerce.Site.Controllers
{
    [Authorize, Route("checkout")]
    public class CheckoutController : Controller
    {
        private readonly IEnderecoStore _enderecoStore;
        private readonly ICarrinhoStore _carrinhoStore;
        private readonly IFreteService _freteService;
        private readonly ICarrinhoService _carrinhoService;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IPedidoService _pedidoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CheckoutController(
            IEnderecoStore enderecoStore,
            ICarrinhoStore carrinhoStore,
            IFreteService freteService,
            ICarrinhoService carrinhoService,
            IGeoposicaoService geoposicaoService,
            IPedidoService pedidoService,
            IHttpContextAccessor httpContextAccessor)
        {
            _enderecoStore = enderecoStore;
            _carrinhoStore = carrinhoStore;
            _freteService = freteService;
            _carrinhoService = carrinhoService;
            _geoposicaoService = geoposicaoService;
            _pedidoService = pedidoService;
            _httpContextAccessor = httpContextAccessor;
        }

        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento()
        {
            var enderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }
            if (!carrinho.FreteSelecionado())
            {
                TempData["ERRO"] = "Selecione o frete";
                return RedirectToAction("Index");
            }
            var cartao = CartaoCredito.Obter().Generate();
            return View(new CheckoutViewModel()
            {
                EnderecosUsuario = enderecosUsuario,
                Carrinho = carrinho,
                CartaoCredito = cartao
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento(CheckoutViewModel model)
        {
            model.EnderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            model.Carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (model.Carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }
            if (!model.IsValid())
            {
                model.Erro = "Concorde com os termos";
                return View(model);
            }


            var pedido = model.GerarPedido(model.Carrinho, model.EnderecosUsuario);
            await _pedidoService.SalvarPedido(pedido, User.Identity.Name);

            await _carrinhoService.LimparCarrinho(User.Identity.Name);

            return View("ConfirmarPedido", pedido);
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var fretes = await _freteService.CalcularCarrinho(carrinho, await _geoposicaoService.GeolocalizarUsuario(), at);
            return View(new CheckoutViewModel()
            {
                OpcoesFrete = fretes,
                Carrinho = carrinho,
            });
        }
    }
}

SkyCommerce/SkyCommerce.Loja/SkyCommerce.Site/Views/Carrinho/Index.cshtml
@using SkyCommerce.Extensions
@model CarrinhoViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('input').on('ifChecked', function (event) {
                //console.log(event.type + ' callback');
                document.getElementById('formFrete').submit();
            });

        });
    </script>
}

<div class="container main-container headerOffset">
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
            <ul class="breadcrumb">

                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="active">Carrinho</li>
            </ul>
        </div>
    </div>
    <!--/.row-->

    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-7 col-xs-6 col-xxs-12 text-center-xs">
            <h1 class="section-title-inner">
                <span>
                    <i class="glyphicon glyphicon-shopping-cart"></i> Seu carrinho
                </span>
            </h1>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-5 rightSidebar col-xs-6 col-xxs-12 text-center-xs">
            <h4 class="caps"><a asp-controller="Home" asp-action="Index"><i class="fa fa-chevron-left"></i> Voltar</a></h4>
        </div>
    </div>
    <!--/.row-->

    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-7">
            <div class="row userInfo">
                <div class="col-xs-12 col-sm-12">
                    <div class="cartContent w100">

                        @if (Model.Carrinho != null)
                        {
                            <table class="cartTable table-responsive" style="width: 100%">
                                <tbody>

                                    <tr class="CartProduct cartTableHeader">
                                        <td style="width: 15%"> Produto</td>
                                        <td style="width: 40%">Detalhes</td>
                                        <td style="width: 10%" class="delete">&nbsp;</td>
                                        <td style="width: 10%">QNT</td>
                                        <td style="width: 15%">Total</td>
                                    </tr>
                                    @foreach (var item in Model.Carrinho.Items)
                                    {
                                        var formRemover = "form" + item.NomeUnico;
                                        var formQuantidade = "formQtd" + item.NomeUnico;
                                        <tr class="CartProduct">
                                            <td class="CartProductThumb">
                                                <div>
                                                    <a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico">
                                                        <img src="@item.Imagem" alt="@item.Produto">
                                                    </a>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="CartDescription">
                                                    <h4><a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico"> @item.Produto </a></h4>

                                                    <div class="price"><span> @item.Valor.ToString("C") </span></div>
                                                </div>
                                            </td>
                                            <td class="delete">
                                                <form asp-controller="Carrinho" id="@formRemover" asp-action="Remover">
                                                    <input type="hidden" name="NomeUnico" value="@item.NomeUnico" />
                                                </form>
                                                <a title="Delete" onclick="document.getElementById('@formRemover').submit();">
                                                    <i class="glyphicon glyphicon-trash fa-2x"></i>
                                                </a>
                                            </td>
                                            <td>

                                                <form asp-controller="Carrinho" id="@formQuantidade" asp-action="Quantidade">
                                                    <input type="hidden" name="NomeUnico" value="@item.NomeUnico" />
                                                    <input class="quanitySniper" type="text" value="@item.Quantidade" name="Quantidade" onchange="document.getElementById('@formQuantidade').submit();">
                                                </form>
                                            </td>
                                            <td class="price">@item.Total.ToString("C")</td>
                                        </tr>
                                    }


                                </tbody>
                            </table>
                        }
                        else
                        {
                            <h3>Carrinho vazio</h3>
                        }

                    </div>
                    <!--cartContent-->

                    <div class="cartFooter w100">
                        <div class="box-footer">
                            <div class="pull-left">
                                <a asp-controller="Home" asp-action="Index" class="btn btn-default">
                                    <i class="fa fa-arrow-left"></i> &nbsp; Continuar comprando
                                </a>
                            </div>
                            @if (Model.Carrinho != null)
                            {
                                <div class="pull-right">
                                    <a asp-controller="Checkout" asp-action="Index" class="btn btn-primary">
                                        Ir para pagamento&nbsp; <i class="fa fa-arrow-right"></i>
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                    <!--/ cartFooter -->

                </div>
            </div>
            <!--/row end-->

        </div>

        @if (Model.Carrinho != null)
        {
            <div class="col-lg-3 col-md-3 col-sm-5 rightSidebar">
                <div class="contentBox">
                    <div class="w100 costDetails">
                        <div class="table-block" id="order-detail-content">
                            <a class="btn btn-primary btn-lg btn-block "
                               title="checkout" asp-controller="Checkout"
                               asp-action="Index"
                               style="margin-bottom: 20px">
                                Seguir para o pagamento &nbsp; <i class="fa fa-arrow-right"></i>
                            </a>

                            <div class="w100 cartMiniTable">
                                <table id="cart-summary" class="std table">
                                    <tbody>
                                        <tr>
                                            <td>Total produtos</td>
                                            <td class="price">@Model.Carrinho.TotalProdutos.ToString("C")</td>
                                        </tr>
                                        <tr style="">
                                            <td>Entrega</td>

                                            @if (Model.Carrinho.TotalProdutos > 200)
                                            {
                                                <td class="price">
                                                    <span class="success">Gratuita</span>
                                                </td>
                                            }
                                            else
                                            {
                                                <td class="price" style="        text-align: left !important;font-size: 12px;">
                                                    <form id="formFrete" asp-controller="Carrinho" asp-action="SelecionarFrete">
                                                        @foreach (var frete in Model.Fretes)
                                                        {
                                                            var selecionado = Model.Carrinho.Frete?.Modalidade == frete.Modalidade ? "checked=\"checked\"" : string.Empty;

                                                            <label><input type="radio" @selecionado name="Modalidade" value="@frete.Modalidade" />@frete.Modalidade: @frete.Valor.ToString("C")</label>
                                                        }
                                                    </form>
                                                </td>
                                            }

                                        </tr>
                                        <tr class="cart-total-price ">
                                            <td>Total (sem impostos.)</td>
                                            <td class="price">@Model.Carrinho.TotalSemImposto.ToString("C")</td>
                                        </tr>
                                        <tr>
                                            <td>Impostos</td>
                                            <td class="price" id="total-tax">@Model.Carrinho.Imposto.ToString("C")</td>
                                        </tr>
                                        @if (Model.Carrinho.Cupom.IsPresent())
                                        {
                                            <tr>
                                                <td> Cupom: @Model.Carrinho.Cupom.Substring(0, 5)</td>
                                                <td class=" site-color" id="total-price">@Model.Carrinho.PercentualDesconto.ToString("N")%</td>
                                            </tr>
                                        }
                                        <tr>
                                            <td> Total</td>
                                            <td class=" site-color" id="total-price">@Model.Carrinho.Total.ToString("C")</td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <div class="input-append couponForm">
                                                    <form asp-controller="Carrinho" id="removerCarrinho" asp-action="Cupom">
                                                        <input class="col-lg-8" id="appendedInputButton" name="Cupom" type="text"
                                                               placeholder="Cupom">
                                                        <button class="col-lg-4 btn btn-success" type="submit">Aplicar!</button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                            <div class="w100 cartMiniTable">
                                <h4>Frete</h4>
                                <table class="table table-responsive">
                                    <tbody>
                                        @foreach (var frete in Model.Fretes)
                                        {
                                            <tr>
                                                <td><b>@frete.Modalidade</b></td>
                                                <td>@frete.Descricao</td>
                                                <td>@frete.Valor.ToString("C")</td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="3">* Gratuito em compras acima de R$ 200,00</td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End popular -->

            </div>
            <!--/rightSidebar-->
        }
    </div>
    <!--/row-->

    <div style="clear:both"></div>
</div>
<!-- /.main-container -->